spring.application.name=backend
spring.datasource.url=jdbc:mariadb://localhost:3307/nli
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


security.jwt.secret-key =VGhpcy1pcy1hLXNlY3JldC1rZXktdGhhdC1pcy1sb25nLWVub3VnaC1mb3ItSFMyNTY=
security.jwt.expiration-time=3600000


# Mail properties
spring.mail.host=hamza.alaouimhamdi@etu.uae.ac.ma
spring.mail.port=587
spring.mail.username=hamza
spring.mail.password=niggasInParis
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

